source "https://rubygems.org"

gem "jekyll", "~> 4.3.2"
gem "webrick", "~> 1.8"
gem "github-pages", group: :jekyll_plugins
gem "just-the-docs"

group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-sitemap"
  gem "jekyll-feed"
  gem "jekyll-redirect-from"
  gem "jekyll-include-cache"
  gem "jekyll-remote-theme"
  gem "jekyll-github-metadata"
  gem "jekyll-lunr-js-search"
end 